---
# @meta description: >
# Collection of handlers includeable by other roles
# @end
# @meta author: [Thilo Solbrig]
galaxy_info:
  role_name: global_handlers
  author: Thilo Solbrig
  description: Collection of handlers includeable by other roles (e.g., via meta dependencies)
  company: ASPICON GmbH
  license: license (MIT)

  min_ansible_version: 2.14.0

  platforms:
    - name: EL
      versions:
        - "6"
        - "7"
        - "8"
        - "9"
    - name: SLES
      versions:
        - "15"

  galaxy_tags: []

dependencies: []
