---
  hostgroup: vbox-si-asm
  role_separation: True
  device_persistence: asmlib
  storage_type: ASM
  #multipath: dm-multipath


  oracle_user: oracle
  oracle_group: oinstall

  install_from_nfs: false
  oracle_sw_copy: False
  oracle_sw_unpack: True
  is_sw_source_local: false
  #oracle_sw_source_www: http://192.168.0.24/orasw/
  #oracle_sw_source_local: /Users/miksan/Downloads/oracle/
  oracle_stage: /u01/stage
  oracle_stage_remote: /media/swrepo

  configure_ntp: true
  configure_motd: true
  configure_interconnect: false
  configure_ssh: true
  configure_host_disks: true

  install_os_packages: True
  configure_epel_repo: true
  configure_public_yum_repo: True
  disable_selinux: false

################ Grid Infrastructure specifics ################
  configure_cluster: false
  oracle_install_version_gi: 12.2.0.1

  oracle_asm_init_dg: crs

  host_fs_layout:
   - vgname: vgora
     state: present
     filesystem:
       - {mntp: /u01, lvname: lvora, lvsize: 100%FREE, fstype: ext4}
     disk:
       - {device: /dev/sdb, pvname: /dev/sdb1}