# Partition & ASM-Label Shared disks
---
  
  - name: ASMlib | Create device to label mappings for asm
    template: src=asm-label-device-mapping.txt.j2 dest={{ oracle_rsp_stage }}/asm-label-device-mapping-{{ item.diskgroup }}.txt
    with_items: asm_diskgroups
    when: master_node
    tags: asmlib

  - name: ASM-storage | Build script to create partitions 
    template: src=part-device.sh.j2 dest={{ oracle_rsp_stage }}/part-device-{{ item.diskgroup }}.sh mode=775
    with_items: asm_diskgroups
    when: master_node 
    tags: asmlib

  - name: ASM-storage | Run script to create partitions
    shell: sh {{ oracle_rsp_stage }}/part-device-{{ item.diskgroup }}.sh
    with_items: asm_diskgroups
    when: master_node
    tags: asmlib

  - include: dm-multipath-kpartx.yml
    when: multipath == 'dm-multipath'

  - name: ASMlib | Build script to create asmlib-labels
    template: src=label-asm-disks.sh.j2 dest={{ oracle_rsp_stage }}/label-asm-disks-{{ item.diskgroup }}.sh mode=775
    with_items: asm_diskgroups
    when: master_node and device_persistence == 'asmlib' 
    tags: asmlib

  - name: ASMlib | Run script to create asmlib-labels
    shell: sh {{ oracle_rsp_stage }}/label-asm-disks-{{ item.diskgroup }}.sh
    with_items: asm_diskgroups
    when: master_node and device_persistence == 'asmlib'
    tags: asmlib

  - name: ASMlib | Rescan ASM disks
    shell: service oracleasm scandisks
    when: device_persistence == 'asmlib'
    tags: asmlib

  - name: ASMlib | List ASM disks
    shell: service oracleasm listdisks
    when: device_persistence == 'asmlib'
    register: listdisks
    tags: asmlib

  - name: List ASM disks
    debug: var=listdisks.stdout_lines
    when: device_persistence == 'asmlib'
    tags: asmlib

  - name: udev | Create device to label mappings for udev
    template: src=udev-label-device-mapping.txt.j2 dest={{ oracle_stage }}/udev/udev-{{ item.diskgroup }}
    with_items: asm_diskgroups
    when: device_persistence == 'udev'
    tags: udev

  - name: udev | Assemble into one mapfile
    assemble: src={{ oracle_stage }}/udev dest={{ oracle_rsp_stage }}/udev-device-input.txt
    when: device_persistence == 'udev'
    tags: udev

  - name: udev | Create script to create rules
    template: src=setup-udev.sh.j2 dest={{ oracle_rsp_stage }}/setup-udev-rules.sh mode=755
    when: device_persistence == 'udev'
    tags: udev

  - name: udev | Run script to create udev rules
    shell: "{{ oracle_rsp_stage }}/setup-udev-rules.sh"
    when: device_persistence == 'udev' 
    tags: udev

  - name: udev | Reload rules
    shell: partprobe; start_udev
    when: device_persistence == 'udev' 
    tags: udev

  - name: udev | List device aliases (register)
    shell: ls -l {{ oracle_asm_disk_string }}
    when: device_persistence == 'udev' 
    tags: udev
    register: lsdevice
 
  - name: List device aliases
    debug: var=lsdevice.stdout_lines
    when: device_persistence == 'udev' 
    tags: udev
   
