---
galaxy_info:
  role_name: common
  author: Mikael Sandstr√∂m (oravirt@gmail.com, http://oravirt.wordpress.com)
  description: Common stuff for ansible-oracle

  license: MIT

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8

  galaxy_tags:
    - database
    - oracle

dependencies: []
