oracle_base: /u01/app/oracle
oracle_home_db: "{% if dbh is defined %}{% if dbh.oracle_home is defined %}{{ dbh.oracle_home }}{% else %}{{ oracle_base}}/{{ dbh.oracle_version_db }}/{{ dbh.home }}{% endif %}{% elif item.0 is defined %}{% if item.0.oracle_home is defined %}{{ item.0.oracle_home}}{% else %}{{ oracle_base }}/{{ item.0.oracle_version_db }}/{{ item.0.home }}{% endif %}{% elif item is defined %}{% if item.oracle_home is defined %}{{ item.oracle_home}}{% else %}{{ oracle_base }}/{{ item.oracle_version_db }}/{{ item.home }}{% endif %}{% endif %}"
db_user: sys
db_password: "{% if dbpasswords is defined and dbpasswords[item.cdb] is defined and dbpasswords[item.cdb][db_user] is defined%}{{dbpasswords[item.cdb][db_user]}}{% else %}{{ default_dbpass}}{% endif%}"
db_mode: sysdba

pdbadmin_user: pdbadmin
pdbadmin_password: "{% if dbpasswords is defined and dbpasswords[item.cdb] is defined and dbpasswords[item.cdb][item.pdb_name] is defined and dbpasswords[item.cdb][item.pdb_name][pdbadmin_user] is defined%}{{dbpasswords[item.cdb][item.pdb_name][pdbadmin_user]}}{% else %}{{ default_dbpass}}{% endif%}"

oracle_env:
       ORACLE_HOME: "{{ oracle_home_db }}"
       LD_LIBRARY_PATH: "{{ oracle_home_db }}/lib"

# oracle_pdbs:
#   - pdb_name: orclpdb
#     cdb: orclcdb
#     state: present
