---
galaxy_info:
  role_name: oradb_manage_pdb
  author: Mikael Sandström
  description: Manage pluggable databases in Oracle
  company: Mikael Sandström

  license: license (MIT)

  min_ansible_version: 2.9.0

  platforms:
    - name: EL
      versions:
        - "6"
        - "7"
        - "8"

  galaxy_tags:
    - database
    - oracle

dependencies:
  - role: orasw_meta
