---
collections:
  - name: opitzconsulting.ansible_oracle
    version: 4.14.0

  # following entry is for development only!
  # - name: opitzconsulting.ansible_oracle
  #   source: ./../../..
  #   type: dir
