apply_patches_db: False
db_homes_config:
  18300-base:
    home: db1-base
    version: 18.3.0.0
    edition: EE
  # 12201-base:
  #   home: db1-base
  #   version: 12.2.0.1
  #   edition: EE
  # 12201-latest:
  #   home: db1-latest
  #   version: 12.2.0.1
  #   edition: EE
  #   opatch_minversion: 12.2.0.1.12
  #   opatchauto:
  #       - patchid: 28183653
  #         patchversion: 12.2.0.1.180717
  #         state: absent
  #         subpatches:
  #             - 28163133
  #             - 28163190
  #       - patchid: 27468969
  #         patchversion: 12.2.0.1.180417
  #         state: absent
  #         subpatches:
  #             - 27674384
  #             - 27464465
  #   opatch:
  #       - patchid: 28140658
  #         state: absent
  # 11204-latest:
  #   home: db1-latest
  #   version: 11.2.0.4
  #   edition: EE
  #   opatch_minversion: 11.2.0.3.6
  #   opatchauto:
  #       - patchid: 27475913
  #         patchversion: 11.2.0.4.180417
  #         state: present
  #         subpatches:
  #             - 27338049
  #             # - 27441052


db_homes_installed:
     - home: 18300-base
       apply_patches: False
       state: present
     # - home: 12201-base
     #   apply_patches: False
     #   state: absent
     # - home: 12201-latest
     #   apply_patches: True
     #   state: absent
     # - home: 11204-latest
     #   apply_patches: True
     #   state: absent
