---
  hostgroup: vbox-si-fs

  oracle_user: oracle
  oracle_group: oinstall

  install_from_nfs: false
  oracle_sw_copy: false
  oracle_sw_unpack: False
  oracle_stage: /u01/stage
  oracle_stage_remote: /media/swrepo
  autostartup_service: true

  configure_ntp: true
  configure_motd: true
  configure_host_disks: true

  install_os_packages: True
  configure_epel_repo: false
  configure_public_yum_repo: false
  disable_selinux: false



  host_fs_layout:
   - vgname: vgora
     state: present
     filesystem:
       - {mntp: /u01, lvname: lvora, lvsize: 100%FREE, fstype: ext4}
     disk:
       - {device: /dev/sdb, pvname: /dev/sdb1}
   - vgname: vgoradata
     state: present
     filesystem:
       - {mntp: /u02, lvname: lvoradata, lvsize: 100%FREE, fstype: xfs}
     disk:
       - {device: /dev/sdc, pvname: /dev/sdc1}
