---
is_sw_source_local: true
oracle_sw_copy: false
oracle_sw_unpack: false

# Directory for Installation-Media
oracle_stage_remote: /tmp

# Example for Remote NFS
# install_from_nfs: true          # Mount NFS-Share?
# nfs_server_sw: 192.168.56.99    # NFS-Server
# nfs_server_sw_path: /sw         # NFS-Share
# oracle_stage_remote: /u01/se    # local mount point for NFS share
