---
galaxy_info:
  role_name: oradb_facts
  author: Thorsten Bruhns
  description: Gather Ansible Facts from database
  company: OPITZ CONSULTING Deutschland GmbH

  license: license (MIT)

  min_ansible_version: 2.9.0

  platforms:
    - name: EL
      versions:
        - "6"
        - "7"
        - "8"

  galaxy_tags:
    - database
    - oracle

dependencies:
  - role: orasw_meta
