---
# defaults file for oradb-manage-grants
configure_cluster: false
oracle_base: /u01/app/oracle

db_user: system
db_password_cdb: "{% if dbpasswords is defined and dbpasswords[item.0.oracle_db_name] is defined and dbpasswords[item.0.oracle_db_name][db_user] is defined%}{{dbpasswords[item.0.oracle_db_name][db_user]}}{% else %}{{ default_dbpass}}{% endif%}"
db_password_pdb: "{% if dbpasswords is defined and dbpasswords[item.0.cdb] is defined and dbpasswords[item.0.cdb][db_user] is defined%}{{dbpasswords[item.0.cdb][db_user]}}{% else %}{{ default_dbpass}}{% endif%}"

db_service_name: "{% if item.0 is defined %}
                    {%- if item.0.oracle_db_unique_name is defined %}{{ item.0.oracle_db_unique_name }}
                    {%- elif item.0.oracle_db_instance_name is defined %}{{ item.0.oracle_db_instance_name }}
                    {%- else %}{{ item.0.oracle_db_name }}
                    {%- endif %}
                  {%- endif %}"

listener_port_template: "{% if item.0.listener_port is defined %}{{ item.0.listener_port }}{% else %}{{ listener_port }}{% endif %}"
listener_port: 1521

user_cdb_password: "{% if dbpasswords is defined and dbpasswords[item.0.oracle_db_name] is defined and dbpasswords[item.0.oracle_db_name][item.1.schema] is defined %}{{dbpasswords[item.0.oracle_db_name][item.1.schema]}}{% else %}{{ default_dbpass}}{% endif%}"
user_pdb_password: "{% if dbpasswords is defined and dbpasswords[item.0.cdb] is defined and dbpasswords[item.0.cdb][item.0.pdb_name] is defined and dbpasswords[item.0.cdb][item.0.pdb_name][item.1.schema] is defined%}{{dbpasswords[item.0.cdb][item.0.pdb_name][item.1.schema]}}{% else %}{{ default_dbpass}}{% endif%}"

oracle_env:
       ORACLE_HOME: "{{ oracle_home_db }}"
       LD_LIBRARY_PATH: "{{ oracle_home_db }}/lib"

attr_name:  "{% if item.1.attributes is defined %}{{item.1.attributes |default (omit) | map(attribute='name') | list }}{% else %}None{%endif%}"
attr_value: "{% if item.1.attributes is defined %}{{item.1.attributes |default (omit) | map(attribute='value') | list }}{% else %}None{%endif%}"


# This is an example of how the profile configuration should look like

# oracle_databases:
#       - home: 12201-base
#         oracle_db_name: orclcdb
#         ....
#         ....
#         profiles:
#             - name: profile1
#               state: present
#               attributes:
#                    - {name: password_reuse_max, value: 7}
#                    - {name: password_reuse_time, value: 500}

