---
galaxy_info:
  role_name: oradb_manage_profiles
  author: Mikael Sandström
  description: Manage database profiles in Oracle
  company: Mikael Sandström

  license: license (MIT)

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8

  galaxy_tags:
    - database
    - oracle

dependencies:
  - role: orasw-meta
