---
- name: install-home-db | Configure oracle-rdbms auto-startup service (systemd.d)
  template:
    src=oracle-rdbms-service.j2
    dest=/etc/systemd/system/oracle-rdbms.service
    owner=root
    mode=0644
  become: true
  become_user: root
  notify:
    - systemd register and reload
  with_items: "{{ db_homes_installed }}"
  when:
    - autostartup_service
    - hostinitdaemon == "systemd"
    - item.state|lower == 'present'
  tags:
    - autostartup_service
    - seclimit    # Update template when ulimits have been chagned as well.
