---
- ansible.builtin.debug: msg="ORACLE_BASE_HOME {{ listener_home_config }}"  # noqa name[missing]
  tags: tnsnames

- name: tnsnames.ora | create IFILE entry in tnsnames.ora
  ansible.builtin.lineinfile:
    line: "IFILE={{ listener_home }}/network/admin/tnsnames_ansible.ora"
    regexp: "^IFILE=/"
    insertbefore: BOF
    path: "{{ listener_home_config }}/network/admin/tnsnames.ora"
    backup: true
    create: true
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"
    state: present
    mode: 0644
  tags: tnsnames

- name: tnsnames.ora | create custom configuration in tnsnames_ansible.ora
  ansible.builtin.blockinfile:
    path: "{{ listener_home_config }}/network/admin/tnsnames_ansible.ora"
    backup: true
    create: true
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"
    state: "{{ tnsinst.state | default('present') }}"
    mode: 0644
    insertafter: "EOF"
    marker: "# {mark} Ansible managed for  {{ tnsinst.tnsname }}"
    block: "{{ lookup('template', 'tnsnames' + oracle_tnsnames_config[tnsinst.tnsname]['tnstemplate'] | default('') + '.ora.j2') }}"
  tags: tnsnames
