---

  master_node: true
  oracle_home_db: "{% if item.0 is defined %}{% if item.0.oracle_home is defined %}{{ item.0.oracle_home}}{% else %}{{ oracle_base }}/{{ item.0.oracle_version_db }}/{{ item.0.home }}{% endif %}{% else %}{% if item.oracle_home is defined %}{{ item.oracle_home }}{% else %}{{ oracle_base }}/{{ item.oracle_version_db }}/{{ item.home }}{% endif %}{% endif %}"
  oracle_stage: /u01/stage
  oracle_rsp_stage: "{{ oracle_stage }}/rsp"
  oracle_inventory_loc: /u01/app/oraInventory
  oracle_base: /u01/app/oracle

  oracle_databases:                                            # Dictionary describing the databases to be installed
        - home: home1                                          # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.1.0.2/racdb)
          oracle_version_db: 12.1.0.2                          # Oracle versiono
          oracle_edition: EE                                   # The edition of database-server (EE,SE,SEONE)
          oracle_db_name: orcl                                 # Database name
          oracle_db_passwd: Oracle123                          # Passwords (sys/system/dbsnm etc)
          oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
          is_container: "false"                                # (true/false) Is the database a container database
          pdb_prefix: pdb
          num_pdbs: 1
          storage_type: FS                                     # Database storage to be used. ASM or FS.
          service_name: orcl_serv                              # Inital service to be created (not in use yet)
          oracle_init_params: "open_cursors=300,processes=700" # Specific parameters to be set during installation. Comma-separated list
          oracle_db_mem_totalmb: 1024                          # Amount of RAM to be used for SGA + PGA
          oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
          redolog_size_in_mb: 100
          state: absent
