---

# master_node: true
role_separation: false
hostgroup: "{{ group_names[0] }}"
cluster_master: "{{ play_hosts[0] }}"
configure_cluster: false

oracle_user: oracle                        # User that will own the Oracle Installations.
grid_user: grid
grid_install_user: "{% if role_separation %}{{ grid_user }}{% else %}{{ oracle_user }}{% endif %}"
oracle_user_home: "/home/{{ oracle_user }}"  # Home directory for oracle_user. Needed for passing in ssh-keys, profiles etc
grid_user_home: "/home/{{ grid_install_user }}"  # Home directory for oracle_user. Needed for passing in ssh-keys, profiles etc
oracle_group: oinstall                          # Primary group for oracle_user.

oracle_sw_source_www: http://www/orasw     # address to all software if using the get_url module when putting software on the host(s)
oracle_sw_source_local: /tmp  # Path to all software if using the copy module when putting software on the host(s)
is_sw_source_local: true
install_from_nfs: false
oracle_sw_copy: "{% if install_from_nfs %}False{% else %}True{% endif %}"
oracle_sw_unpack: "{% if install_from_nfs %}False{% else %}True{% endif %}"
nfs_server_sw: nfsserver
nfs_server_sw_path: /path/to/orasw

oracle_stage: /u01/stage
oracle_stage_remote: "{{ oracle_stage }}"
oracle_stage_install: "{% if not oracle_sw_copy and not oracle_sw_unpack%}{{ oracle_stage_remote }}{% else %}{{ oracle_stage }}{% endif %}"
oracle_base: /u01/app/oracle
oracle_rsp_stage: "{{ oracle_stage }}/rsp"
oracle_patch_stage: "{{ oracle_stage }}/patches"
oracle_patch_stage_remote: "{{ oracle_stage_remote }}/patches"
oracle_patch_install: "{% if not oracle_sw_copy and not oracle_sw_unpack%}{{ oracle_patch_stage_remote }}{% else %}{{ oracle_patch_stage }}{% endif %}"
oracle_inventory_loc: /u01/app/oraInventory
oracle_home_gi: "{% if configure_cluster %}{{ oracle_home_gi_cl }}{% else %}{{ oracle_home_gi_so }}{% endif %}"
oracle_home_gi_cl: "/u01/app/{{ oracle_install_version_gi }}/grid"  # ORACLE_HOME for Grid Infrastructure (Clustered)
oracle_home_gi_so: "{{ oracle_base }}/{{ oracle_install_version_gi }}/grid"  # ORACLE_HOME for Grid Infrastructure (Stand Alone)

oracle_hostname: "{{ ansible_fqdn }}"                            # Full (FQDN) name of the host
ocm_response_file: "{{ oracle_patch_stage }}/{{ oracle_install_version_gi }}/ocm.rsp"

apply_patches_gi: false
patch_before_rootsh: true

gi_patches:
  18.3.0.0:
    opatchauto: []
    opatch: []
  12.2.0.1:
    opatch_minversion: 12.2.0.1.12
    opatchauto:
      - patchid: 28183653
        patchversion: 12.2.0.1.180717
        state: present
        subpatches:
          - 28163133
          - 28163190
          - 28163235
          - 26839277
          - 27144050
    opatch: []
  12.1.0.2:
    opatch_minversion: 12.1.0.1.7
    opatchauto:
      - patchid: 27967747
        patchversion: 12.1.0.2.180717
        state: present
        subpatches:
          - 26983807
          - 27547329
          - 27762253
          - 27762277
    opatch: []
  11.2.0.4:
    opatch_minversion: 11.2.0.3.6
    opatchauto:
      - patchid: 27967757
        patchversion: 11.2.0.4.180717
        state: present
        subpatches:
          - 27734982
          - 27441052
          - 27959254
    opatch: []
