---
galaxy_info:
  role_name: orahost_meta
  author: Thorsten Bruhns
  description: meta role used by other roles to share variable defaults.
  company: Thorsten Bruhns

  license: license (MIT)

  min_ansible_version: 2.9.0

  platforms:
    - name: EL
      versions:
        - "6"
        - "7"
        - "8"

  galaxy_tags: []

dependencies: []
