- name: Manage tablespaces (db/cdb)
  oracle_tablespace:
        hostname={{ ansible_hostname }}
        port={{ listener_port_template }}
        service_name={{ db_service_name }}
        user={{ db_user }}
        password={{ db_password_cdb}}
        tablespace={{ item.1.name }}
        datafile={{ item.1.datafile |default(omit)}}
        numfiles={{ item.1.numfiles |default(omit)}}
        bigfile={{ item.1.bigfile |default(omit) }}
        size={{ item.1.size |default(omit)}}
        autoextend={{ item.1.autoextend |default(omit)}}
        next={{ item.1.next |default(omit)}}
        maxsize={{ item.1.maxsize |default(omit)}}
        content={{ item.1.content |default(omit)}}
        state={{ item.1.state |default('present')}}
  environment: "{{oracle_env}}"
  run_once: "{{ configure_cluster }}"
  with_subelements:
      - "{{oracle_databases}}"
      - tablespaces
      - flags:
        skip_missing: True
  loop_control:
      label: "port: {{ listener_port_template }} service: {{ db_service_name }} tablespace: {{ item.1.name }} content: {{ item.1.content |default(omit)}} state: {{ item.1.state |default('present')}}"
  when: oracle_databases is defined and item.1 is defined and item.0.state |upper == 'PRESENT'
  tags: tablespace

- name: Manage tablespaces (pdb)
  oracle_tablespace:
        hostname={{ ansible_hostname }}
        port={{ listener_port_template }}
        service_name={{ item.0.pdb_name }}
        user={{ db_user }}
        password={{ db_password_pdb}}
        tablespace={{ item.1.name }}
        datafile={{ item.1.datafile |default(omit)}}
        numfiles={{ item.1.numfiles |default(omit)}}
        bigfile={{ item.1.bigfile |default(omit) }}
        size={{ item.1.size |default(omit)}}
        autoextend={{ item.1.autoextend |default(omit)}}
        next={{ item.1.next |default(omit)}}
        maxsize={{ item.1.maxsize |default(omit)}}
        content={{ item.1.content |default(omit)}}
        state={{ item.1.state |default('present')}}
  environment: "{{oracle_env}}"
  run_once: "{{ configure_cluster }}"
  with_subelements:
      - "{{oracle_pdbs}}"
      - tablespaces
      - flags:
        skip_missing: True
  when: oracle_pdbs is defined and item.1 is defined and item.0.state |upper == 'PRESENT'
  loop_control:
      label: "port: {{ listener_port_template }} service: {{ item.0.pdb_name }} tablespace: {{ item.1.name }} content: {{ item.1.content |default(omit)}} state: {{ item.1.state |default('present')}}"
  tags: tablespace
