---
__patchru_id: >-
  {{ db_homes_config[dbh.home]['opatchauto'] | map(attribute='patchid') | first }}

__patchru_dir: >-
  /u01/stage/patches/19.3.0.0/35940989/35940989

# internal use only
_oraswdb_install_db_responsefile: "{{ dbh.home }}_{{ ansible_hostname }}.rsp"

# _oraswdb_install_opatchid_list: |-
#   {{ db_homes_config[dbh.home]['opatch'] | default({})
#   | selectattr('state', 'match', 'present')
#   | join(',') }}

# _oraswdb_install_applyruopatchauto: |-
#   {{ gi_patches[oracle_install_version_gi]['opatchauto']
#   | selectattr('state', 'equalto', 'present') | list | first }}

_oraswdb_install_opatchauto_dirlist: |-
  {% for __patch_dict in db_homes_config[dbh.home]['opatchauto'] | default({}) | selectattr('state', 'match', 'present') -%}
  {{- _oraswdb_install_patch_dir_prefix }}/{{ __patch_dict.path
  | default((__patch_dict.patchid | string)+ '/' + (__patch_dict.patchid | string)) -}}
  {%- if not loop.last %},{% endif -%}
  {%- endfor %}

_oraswdb_install_patches_dirlist: |-
  {% for __patch_dict in db_homes_config[dbh.home]['opatch'] | default({}) | selectattr('state', 'match', 'present') -%}
  {{- _oraswdb_install_patch_dir_prefix }}/{{ __patch_dict.path
  | default((__patch_dict.patchid | string)+ '/' + (__patch_dict.patchid | string)) -}}
  {%- if not loop.last %},{% endif -%}
  {%- endfor %}

_oraswdb_install_patch_dir_prefix: |-
  {{ oracle_sw_copy | bool | ternary(oracle_stage, oracle_stage_remote) }}/patches/{{ db_version }}

_oraswdb_install_patch_unarchive_dir: "{{ oracle_patch_stage }}/{{ db_version }}/{{ _oraswdb_install_patch_upisubdir }}/"
_oraswdb_install_patch_upisubdir: >-
  {{ osp_loop.unique_patchid is defined
  | ternary(osp_loop.unique_patchid,
  |  osp_loop.patchid) }}/


# Mapping for installation media for Oracle
_oraswdb_install_oracle_sw_image_db:
  - {filename: LINUX.X64_213000_db_home.zip, version: 21.3.0.0, creates: 'install/.img.bin'}
  - {filename: LINUX.X64_193000_db_home.zip, version: 19.3.0.0, creates: 'install/.img.bin'}
  - {filename: LINUX.X64_180000_db_home.zip, version: 18.3.0.0, creates: 'install/.img.bin'}
  - {filename: linuxx64_12201_database.zip, version: 12.2.0.1, creates: 'database/runInstaller'}
  - {filename: linuxamd64_12102_database_1of2.zip, version: 12.1.0.2, creates: 'database/stage/sizes/oracle.server.Custom.sizes.properties'}
  - {filename: linuxamd64_12102_database_2of2.zip, version: 12.1.0.2, creates: 'database/install/.oui'}
  - {filename: linuxamd64_12c_database_1of2.zip, version: 12.1.0.1, creates: 'database/runInstaller'}
  - {filename: linuxamd64_12c_database_2of2.zip, version: 12.1.0.1, creates: 'database/runInstaller'}
  - {filename: p13390677_112040_Linux-x86-64_1of7.zip, version: 11.2.0.4, creates: 'database/install/resource/cons_zh_TW.nls'}
  - {filename: p13390677_112040_Linux-x86-64_2of7.zip, version: 11.2.0.4, creates: 'database/stage/Components/oracle.db/11.2.0.4.0/1/DataFiles/filegroup18.jar'}
  - {filename: p10404530_112030_Linux-x86-64_1of7.zip, version: 11.2.0.3, creates: 'database/readme.html'}
  - filename: p10404530_112030_Linux-x86-64_2of7.zip
    version: 11.2.0.3
    creates: 'database/stage/Components/oracle.sysman.console.db/11.2.0.3.0/1/DataFiles/filegroup2.jar'

_oraswdb_install_oracle_directories:
  - {name: "{{ oracle_stage }}", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775}
  - {name: "{{ oracle_rsp_stage }}", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775}
  - {name: "{{ oracle_tmp_stage }}", owner: root, group: root, mode: "u+rwx,g+rwx,o+rwxt"}
  - {name: "{{ oracle_base }}", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775}
  - {name: "{{ oracle_base }}/cfgtoollogs", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775}
  - {name: "{{ oracle_base }}/admin", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775}
  - {name: "{{ oracle_base }}/audit", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775}
  - {name: "{{ oracle_base }}/cfgtoollogs/dbca", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775}
  - {name: "{{ oracle_base }}/cfgtoollogs/sqlpatch", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775}
  - {name: "{{ oracle_base }}/cfgtoollogs/netca", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775}
  - {name: "{{ oracle_user_home }}/{{ scripts_folder }}", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775}

# choptcheck is a dummy for 'creates' during chopt-task to force an execution
_oraswdb_install_choptcheck: "{% if oraswdb_install_forcechopt | bool %}dochopt{% endif %}"

_oraswdb_install_dbh_stat: >-
  {{ stat_dbh_installed.results
  | selectattr('invocation.module_args.path', 'equalto', (db_homes_config[dbh.home]['oracle_home'] + '/root.sh'))
  | list | first
  }}

_local_oracle_sw_image_db: >-
  {{ db_homes_config[dbh.home].imagename
      | default((_oraswdb_install_oracle_sw_image_db
        | selectattr('version', 'equalto', db_homes_config[dbh.home]['version'])
        | list)[0]['filename']
      ) }}

_oraswdb_install_home_type: >-
  {{ ((oracle_databases | default([]))
      | selectattr('home','equalto',dbh.home)
      | selectattr('state','equalto','present')
      | map(attribute='oracle_db_type',default='SI')
      | unique)[0] }}
