# GI
default_gipass: Oracle123
sysasmpassword: Oracle_123
asmmonitorpassword: Oracle_123

# DB
default_dbpass: Oracle123
dbpasswords:
      orclcdb:
        system: Oracle_123
        sys: Oracle_123
        dbsnmp: Oracle_123
        pdbadmin: Oracle_456
        orclpdb: 
           appuser1: appuser1

