---
galaxy_info:
  role_name: oradb-manage-tablespace
  author: Mikael Sandstr√∂m (oravirt@gmail.com, http://oravirt.wordpress.com)
  description: Manage Tablespaces in Oracle

  license: MIT

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8

  galaxy_tags:
    - database
    - oracle

dependencies:
  - role: orasw-meta
