---
# tasks file for manage-db-users
- name: Manage profiles (cdb)
  oracle_profile:
          name={{ item.1.name }}
          state={{ item.1.state }}
          attribute_name={{ attr_name |default (omit)}}
          attribute_value={{ attr_value  |default (omit)}}
          hostname={{ ansible_hostname }}
          port={{ listener_port_template }}
          service_name={{ db_service_name }}
          user={{ db_user }}
          password={{ db_password_cdb}}
  with_subelements:
      - "{{ oracle_databases }}"
      - profiles
      - flags:
        skip_missing: True
  environment: "{{oracle_env}}"
  loop_control:
      label: "home: {{ item.0.home }} db_name: {{ item.0.oracle_db_name }} Profile: {{ item.1.name }} attributes: {{ item.1.attributes }}"
  when: oracle_databases is defined and item.0.state|lower == 'present' and item.1 is defined
  run_once: "{{ configure_cluster }}"
  become_user: "{{ oracle_user }}"
  tags: dbprofiles

- name: Manage profiles (pdb)
  oracle_profile:
          name={{ item.1.name }}
          state={{ item.1.state }}
          attribute_name={{ attr_name |default (omit)}}
          attribute_value={{ attr_value  |default (omit)}}
          hostname={{ ansible_hostname }}
          port={{ listener_port_template }}
          service_name={{ item.0.pdb_name }}
          user={{ db_user }}
          password={{ db_password_pdb}}
  with_subelements:
      - "{{ oracle_pdbs }}"
      - profiles
      - flags:
        skip_missing: True
  environment: "{{oracle_env}}"
  loop_control:
      label: "home: {{ item.0.home }} CDB: {{ item.0.cdb }} PDB: {{ item.0.pdb_name }} Profile: {{ item.1.name }} attributes: {{ item.1.attributes }}"
  when: oracle_pdbs is defined and item.0 is defined and item.0.state|lower == 'present' and item.1 is defined
  run_once: "{{ configure_cluster }}"
  become_user: "{{ oracle_user }}"
  tags: dbprofiles
