---
- name: Database Server Database Creation
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  roles:
    - opitzconsulting.ansible_oracle.oradb_manage_db
    - opitzconsulting.ansible_oracle.oradb_manage_pdb
    - opitzconsulting.ansible_oracle.oradb_manage_parameters
    - opitzconsulting.ansible_oracle.oradb_manage_tablespace
    - opitzconsulting.ansible_oracle.oradb_manage_redo
    - opitzconsulting.ansible_oracle.oradb_manage_profiles
    - opitzconsulting.ansible_oracle.oradb_manage_statspack
    - opitzconsulting.ansible_oracle.oradb_manage_roles
    - opitzconsulting.ansible_oracle.oradb_manage_users
    - opitzconsulting.ansible_oracle.oradb_manage_grants
    - opitzconsulting.ansible_oracle.oradb_manage_services
    - opitzconsulting.ansible_oracle.oradb_rman
