---
- name: Import_playbook dev-sec
  import_playbook: dev-sec.yml
- name: Import_playbook os
  import_playbook: os.yml
- name: Import_playbook sql-zauberkastern
  import_playbook: sql-zauberkastern.yml
- name: Import_playbook swgi
  import_playbook: swgi.yml
- name: Import_playbook swdb
  import_playbook: swdb.yml
- name: Import_playbook manage-db
  import_playbook: manage-db.yml
